# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Sky' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sky
  pod 'RxSwift',    '4.5.0'
  pod 'RxCocoa',    '4.5.0'
  pod 'Alamofire',      '4.8.2'
  
end
